version: '3.5'
services:

        p1:
                build:
                        context: p1
                container_name: p1
                restart: always
                networks:
                        - compose_network
networks:
        compose_network:
                external:
                        name: compose_network
