version: '3.4'
services:
        ngx:
                image: nginx:1.16.0-alpine-perl
                container_name: ngx
                ports:
                        - "80:80"
                volumes:
                        - ./ngx/nginx.conf:/etc/nginx/nginx.conf
                restart: always

